### ISSUE TITLE
Add supply/demand weights to statistics

### ISSUE THREAD

**Issue by Nakroma** [nexus-devs/warframe-nexus#17]
70% supply and 30% demand means 3 buying is the same as 7 selling for `avg`

**Comment by Kaptard** [comment]
Nevermind this. Stats should be as transparent as possible, i.e. not tempered with in any way. Shouldn't give in to that notion of displaying the "correct price" (free market duh, there is none). 
To fix the problem, the new UI has options to show stats by selling/buying orders separately.
